fieldLayouts:
  0fb7a1e2-da23-40b8-95ba-78b6fe2379d6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 76099428-f3d4-42a7-9bb8-08f425b41461 # Organisation Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6d354976-d845-4bdd-a94b-9ccec9642cdf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e0ee7443-387e-4be3-a64f-3c5ae52be354 # Organisation Email
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 023b696f-3d15-4210-8ae4-8be925f5a5ec
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 54daa4d7-b5cf-4458-9e19-67155be19343 # Organisation Phone
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9ce71977-40a2-4c02-ba33-64aed7288f82
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ab91f872-7263-4250-b647-317386f8f679 # Organisation Address
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0af7fd52-8db6-48d5-9547-7f872109f5d6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 70d3e848-905a-4246-a20b-02c24af51402 # Organisation Address Postal Code 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e3cb225d-2125-441b-941b-09bae4e7bf55
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 74d5a128-4fbc-4ea8-a7d7-c828e87680ff # Organisation Address Region
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 285597e8-3291-4079-a8d8-f0f08b58337b
            userCondition: null
            warning: null
            width: 100
        name: 'Organisational Information'
        uid: 8ad34ae0-1b88-4f1a-8750-fe625ab08912
        userCondition: null
handle: organisationInfo
name: 'Organisational Information'
sortOrder: 4
