fieldLayouts:
  de4e4c7b-fb8e-45c9-8a6d-51a6f8b3f033:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d641ef2d-f0a1-4a0d-b648-642c98a7e5bb # Article Placeholder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4e69b539-8038-4810-8e8e-071577301d5a
            userCondition: null
            warning: null
            width: 100
        name: Placeholders
        uid: 5c70f1a7-ef65-43a7-9d58-8e1444e6f00c
        userCondition: null
handle: placeholders
name: Placeholders
sortOrder: 7
