fieldLayouts:
  46e0492f-cca2-4117-b19e-61e21e7a4882:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 6adae06b-d46a-4585-bcf9-4e1d96f42161
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 090a0621-fdf8-40c9-b3cc-79fbc498e741
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8c9be2b5-73bf-4f32-8fd2-fc36a109dbab # Default Optimisations
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 56fdde5f-a5b3-468d-bde0-a086671f5729
            userCondition: null
            warning: null
            width: 100
        name: 'Image Optimisations'
        uid: 88ad4f7b-c4bb-4d81-a4b5-816d8091c888
        userCondition: null
fs: ctas
handle: ctas
name: CTAs
sortOrder: 16
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ctas
transformSubpath: ''
