fieldLayouts:
  ca18d39f-38e1-4808-bad1-4baf3554fff0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 9a837c3c-e9c3-4bcd-b690-0bf6b385313d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 82b2d336-10cd-42fc-9b59-3844b4296ae6
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8411ab0f-47f3-4c38-ad3b-f449f6bfe1f5 # Small Gallery Optimisation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 83abb01d-11c5-4369-ba7f-d2f913eabba3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 62060b0e-9ae6-4b5a-a779-469967724b21 # Large Gallery Optimisation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b3fede81-d7e6-4dd3-a2ac-53f6e8f45892
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5527a397-226d-4a44-a929-1133169e498a # Square Gallery Optimisation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 37ca40a5-ada4-4e3f-a8f3-78b497b0ef7d
            userCondition: null
            warning: null
            width: 100
        name: 'Image Optimisation'
        uid: 54bc29bf-39a2-4ac4-afc2-5f6d79c955bd
        userCondition: null
fs: gallery
handle: gallery
name: Gallery
sortOrder: 18
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: gallery
transformSubpath: ''
