fieldLayouts:
  71c16d8d-217c-465a-b2d5-fe29e040c582:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: e287dddc-4eb5-48a3-8bac-bd4c38c3ce0e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 40d270b3-10dc-4af3-9663-ef65b2609080
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2b6794f2-86c4-486e-ad7e-a162752af5ef # Grid 50% Optimisations
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3e189e9-7952-4520-8860-de97b44e06c4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0f7ba706-766a-4187-950b-1e24b7b30eeb # Grid 50% Square Optimisations
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 46cb1068-cdf5-4636-9b96-827fbd1b6b5d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a2754e8b-3bc4-46e8-a8e4-45f15fd7590a # Grid 33% Optimisations
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d87d2111-a911-4fc2-af37-4c23899557df
            userCondition: null
            warning: null
            width: 100
        name: 'Image Optimisation'
        uid: 4b3e4fa0-6ae1-43c6-a3ca-b4c5af652ffa
        userCondition: null
fs: grids
handle: grid
name: Grids
sortOrder: 17
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: grids
transformSubpath: ''
