fieldLayouts:
  f318d770-a765-4ecf-b1b7-bedccdc680e9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 9ce3d919-4eaa-49cc-a0a2-e9dbaf3f26bd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8c97d729-f02a-4a39-956f-67619abcef38
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9ea88c8c-ff9b-40b0-94d4-e7eb1b8227a6 # Hero Optimisations
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d005c434-6981-4339-aa7c-34e002d0852a
            userCondition: null
            warning: null
            width: 100
        name: 'Image Optimisations'
        uid: e5c345c8-b11b-45d1-b4be-8f0347bffb9d
        userCondition: null
fs: heroGraphics
handle: heroGraphics
name: 'Hero Graphics'
sortOrder: 22
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: heroGraphics
transformSubpath: ''
