fieldLayouts:
  fd28fb17-12cb-460e-b6bd-7ef53ef732a4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 757a0de0-a4a4-47ef-9b6b-03b8cf7cc95c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0aae719a-2dcb-4508-ae12-c41e5e810e90
        userCondition: null
fs: media
handle: media
name: Media
sortOrder: 24
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
