fieldLayouts:
  94a318e7-f6e9-44c3-8d03-bac7cfa4576c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 123206c0-6cca-4364-87fb-b68025b9d6a7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e61a8be7-73ba-4934-b6b8-066209794ff0
        userCondition: null
fs: media
handle: media
name: Media
sortOrder: 21
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: media
transformSubpath: ''
