fieldLayouts:
  83cff03f-309e-48f4-9061-6524dd62714f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: c7b88907-58b3-403d-9f24-81a11a320f12
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9647ee5d-163c-4374-8b2b-8a105b5671ae
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7c663d4b-8df0-42ba-af70-699dc9d51210 # OG optimisations
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4b70a57f-e832-4708-9e93-e063dc8bc669
            userCondition: null
            warning: null
            width: 100
        name: 'Image optimisations'
        uid: 7319cedc-7e05-4f7b-b940-047003febf7f
        userCondition: null
fs: og
handle: og
name: OG
sortOrder: 20
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
