fieldLayouts:
  84c59ca6-53b1-45fc-b7a4-23f22e6d591f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 834df4f8-0089-4423-aa51-2ff10ac182b7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2d3f87dd-0c7e-4c0f-b773-ccbab67e9fd9
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7c663d4b-8df0-42ba-af70-699dc9d51210
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd7d4669-ebcf-4981-adae-1320ccffbaa7
            userCondition: null
            warning: null
            width: 100
        name: 'Optimized Images'
        uid: 0a24452e-fb2c-4007-b772-5475fecf828c
        userCondition: null
fs: teasers
handle: teasers
name: Teasers
sortOrder: 22
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
