defaultPlacement: end
enableVersioning: false
handle: homepage
name: Homepage
propagationMethod: all
siteSettings:
  5da841b1-ca0d-46ff-8bb1-04d6c889ac54: # Percipio
    enabledByDefault: true
    hasUrls: true
    template: _organisms/page.twig
    uriFormat: __home__
type: single
