field: 25a7de28-66b5-4a4d-a909-6c20b7468030 # Docs Builder
fieldLayouts:
  87271102-bac8-45c6-8a59-fd6668c268f6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3fcd1551-0a7b-452d-ac70-189fec27de1e # Body Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7396ecb8-64d3-4423-8d5b-7605c0258dbe
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 838e225a-6364-4754-9e2b-10868bf36f09
        userCondition: null
fields:
  3fcd1551-0a7b-452d-ac70-189fec27de1e: # Body Content
    columnSuffix: aluqjcuh
    contentColumnType: text
    fieldGroup: null
    handle: article
    instructions: null
    name: 'Body Content'
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Content.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: article
name: 'Article Body'
sortOrder: 2
