field: cf635815-1a46-4527-9d6f-f0544d9019bf # Hero
fieldLayouts:
  0204e29e-3538-40d2-84da-14d870a71a69:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 280b8574-b8df-436b-b052-db741110ca41 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 41dc6161-00b0-42c6-8d93-2b6d945a5ae1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8d73f01a-b357-41a4-8813-79cb2a3bf692
        userCondition: null
fields:
  280b8574-b8df-436b-b052-db741110ca41: # Description
    columnSuffix: oirvpbnc
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: 'Leave blank if you want to use the generic metadescription'
    name: Description
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: description
name: Description
sortOrder: 2
