field: cf635815-1a46-4527-9d6f-f0544d9019bf # Hero
fieldLayouts:
  562911e0-e0aa-4187-9b87-a272ab9d7551:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 98917994-bbbe-4ccb-a18f-d046e1e20b9e # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 59c78828-aad8-4baf-8cff-2a92708764b2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8283dbf1-758e-466b-9dba-53608a97c6a0
        userCondition: null
fields:
  98917994-bbbe-4ccb-a18f-d046e1e20b9e: # Heading
    columnSuffix: rrggyccf
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: 'Leave the heading blank to use the title of the entry as the hero heading'
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: heading
name: Heading
sortOrder: 1
