field: 1755ebbe-91fc-4a2a-80cb-667cc2cf1795 # Locations
fieldLayouts:
  baf243cf-7afd-4ac6-beb6-80d94a45203c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c2249c59-46a5-435d-ab41-42bb543e2875 # City
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2976e338-4846-471c-9267-cd07723e7e76
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d5dde356-9f59-4da4-ad17-e3d7825da610 # Country
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16c946af-1a49-47b6-8efd-a54248c339d8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3d10daf6-be5c-4949-b93d-78a24883ef55 # Longitude
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e00db133-c5b9-4e33-b9cf-92aee8a39f28
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 12994466-6e49-4c20-9577-9d8b8ff8146c # Latitude
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf63a8f8-7043-4dd6-8497-5a76a78ff869
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2ff610e8-7674-4579-a502-37c960213b9b
        userCondition: null
fields:
  3d10daf6-be5c-4949-b93d-78a24883ef55: # Longitude
    columnSuffix: mnceoamp
    contentColumnType: 'decimal(15,5)'
    fieldGroup: null
    handle: longitude
    instructions: 'Add the locations longitude for the local weather'
    name: Longitude
    searchable: false
    settings:
      decimals: 5
      defaultValue: null
      max: null
      min: null
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  12994466-6e49-4c20-9577-9d8b8ff8146c: # Latitude
    columnSuffix: yovmvqft
    contentColumnType: 'decimal(15,5)'
    fieldGroup: null
    handle: latitude
    instructions: 'Add the locations longitude for the local weather'
    name: Latitude
    searchable: false
    settings:
      decimals: 5
      defaultValue: null
      max: null
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  c2249c59-46a5-435d-ab41-42bb543e2875: # City
    columnSuffix: cstvrrly
    contentColumnType: text
    fieldGroup: null
    handle: city
    instructions: null
    name: City
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d5dde356-9f59-4da4-ad17-e3d7825da610: # Country
    columnSuffix: igzxxybu
    contentColumnType: text
    fieldGroup: null
    handle: country
    instructions: null
    name: Country
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: office
name: Office
sortOrder: 1
