field: 25a7de28-66b5-4a4d-a909-6c20b7468030 # Docs Builder
fieldLayouts:
  06b7da95-7016-4f85-9994-892d560641be:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ea5447b7-30bf-4631-980d-45a642e05f85 # Info
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 421c5226-d916-4564-b7bd-49477e4e54ff
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 914c2a29-e3ee-434c-9576-1e545ab7258f
        userCondition: null
fields:
  ea5447b7-30bf-4631-980d-45a642e05f85: # Info
    columnSuffix: ksdpuxgo
    contentColumnType: text
    fieldGroup: null
    handle: info
    instructions: null
    name: Info
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Simple.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: quote
name: Info
sortOrder: 4
