columnSuffix: dmcjwtxi
contentColumnType: text
fieldGroup: b692e225-204e-4347-bbca-cc383d5dee6a # Plugins
handle: activeInstalls
instructions: 'plugin active installs'
name: 'Active Installs'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
