columnSuffix: null
contentColumnType: string(1120)
fieldGroup: b2330e68-6c4a-45ab-b5b1-8a510f75ce4f # General
handle: description
instructions: 'Used in the card, Google search results and when this page is shared on social media sites'
name: Description
searchable: true
settings:
  byteLimit: null
  charLimit: 280
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
