columnSuffix: null
contentColumnType: text
fieldGroup: d08a0d16-0e00-49e6-9cd4-465fa2d65d7d # Errors
handle: errorHeadline
instructions: null
name: 'Error Headline'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
