columnSuffix: null
contentColumnType: string
fieldGroup: b2330e68-6c4a-45ab-b5b1-8a510f75ce4f # General
handle: hero
instructions: null
name: Hero
searchable: false
settings:
  blockTypeFields: 0
  changedFieldIndicator: 1817095208
  columns:
    __assoc__:
      -
        - c18dd467-de1a-4fee-b9b8-51d65c7f27b5 # Heading
        -
          __assoc__:
            -
              - width
              - ''
      -
        - e664a01c-373d-4a79-8e60-404814e10ff9 # Description
        -
          __assoc__:
            -
              - width
              - ''
      -
        - a2442b3f-add5-4d87-97a4-76aa573ea45a # CTA
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_hero}}'
  fieldLayout: matrix
  maxRows: null
  minRows: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: null
  staticField: true
translationKeyFormat: null
translationMethod: none
type: verbb\supertable\fields\SuperTableField
