columnSuffix: ohpswgcc
contentColumnType: text
fieldGroup: 1dd95078-7c8a-4ef7-8a16-e33a5341dadb # Image Optimisations 
handle: optimizeCardSmall
instructions: null
name: 'Small Cards Optimisation'
searchable: false
settings:
  displayDominantColorPalette: true
  displayLazyLoadPlaceholderImages: true
  displayOptimizedImageVariants: true
  ignoreFilesOfType:
    - image/svg
    - image/gif
  variants:
    -
      __assoc__:
        -
          - width
          - '1200'
        -
          - useAspectRatio
          - '1'
        -
          - aspectRatioX
          - '4'
        -
          - aspectRatioY
          - '5'
        -
          - retinaSizes
          -
            - '1'
        -
          - quality
          - '82'
        -
          - format
          - ''
    -
      __assoc__:
        -
          - width
          - '992'
        -
          - useAspectRatio
          - '1'
        -
          - aspectRatioX
          - '4'
        -
          - aspectRatioY
          - '5'
        -
          - retinaSizes
          -
            - '1'
        -
          - quality
          - '82'
        -
          - format
          - ''
    -
      __assoc__:
        -
          - width
          - '768'
        -
          - useAspectRatio
          - '1'
        -
          - aspectRatioX
          - '16'
        -
          - aspectRatioY
          - '9'
        -
          - retinaSizes
          -
            - '1'
        -
          - quality
          - '60'
        -
          - format
          - ''
    -
      __assoc__:
        -
          - width
          - '576'
        -
          - useAspectRatio
          - '1'
        -
          - aspectRatioX
          - '4'
        -
          - aspectRatioY
          - '5'
        -
          - retinaSizes
          -
            - '1'
        -
          - quality
          - '60'
        -
          - format
          - ''
translationKeyFormat: null
translationMethod: none
type: nystudio107\imageoptimize\fields\OptimizedImages
