columnSuffix: null
contentColumnType: text
fieldGroup: 1572f461-2a67-47a4-a36c-80839168bcb7 # Globals
handle: organisationAddress
instructions: null
name: 'Organisation Address'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
