columnSuffix: null
contentColumnType: datetime
fieldGroup: 58eccc39-1c9e-45ac-bae8-465deff69786 # Team
handle: startDate
instructions: 'Enter the team member their date they started working for Percipio.London'
name: 'Started working at Percipio.London'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 30
  showDate: true
  showTime: false
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
