columnSuffix: fdgjyvvm
contentColumnType: text
fieldGroup: d8cd0188-93b8-4702-83ab-558ab8cfb6ef # Schools
handle: street
instructions: null
name: Street
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
