columnSuffix: sdnijyrn
contentColumnType: text
fieldGroup: b36a8fe8-30c1-47a6-a6bd-47424acd50f5 # School
handle: town
instructions: null
name: Town
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
