changedFieldIndicator: 1299311386
field: cf635815-1a46-4527-9d6f-f0544d9019bf # Hero
fieldLayouts:
  586c9ac1-2276-49a2-b2d0-8e6042348a76:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c18dd467-de1a-4fee-b9b8-51d65c7f27b5 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 27fb4a6c-fbd1-4f04-a927-e02b871dd1dd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e664a01c-373d-4a79-8e60-404814e10ff9 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 36998803-a5e9-4080-aa4b-e5c1ed6ba33a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a2442b3f-add5-4d87-97a4-76aa573ea45a # CTA
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bfd07a0b-edbc-4a4a-aae8-d72ed2f7137e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7ac3da87-9d00-41d9-a3d8-8faa82b16e8a
        userCondition: null
fields:
  a2442b3f-add5-4d87-97a4-76aa573ea45a: # CTA
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: target
    instructions: null
    name: CTA
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: false
      autoNoReferrer: false
      customTextMaxLength: 0
      customTextRequired: false
      defaultLinkName: asset
      defaultText: ''
      enableAllLinkTypes: false
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: false
        email:
          allowAliases: false
          disableValidation: false
          enabled: false
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: false
        url:
          allowAliases: false
          disableValidation: false
          enabled: false
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
  c18dd467-de1a-4fee-b9b8-51d65c7f27b5: # Heading
    columnSuffix: whbkzldz
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: 'Leave the heading blank to use the title of the entry as the hero heading'
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e664a01c-373d-4a79-8e60-404814e10ff9: # Description
    columnSuffix: whpflwbo
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: 'Leave blank if you want to use the generic metadescription'
    name: Description
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
