fieldLayouts:
  ab0a57c7-97b7-45bd-bba3-2b0d1c0a782c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cc6e828b-6f92-4b35-b464-61ef06080689
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dbc7a062-ef19-48ca-bd6f-acda62a18b78 # Hero Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1b9ed13c-0253-4d3f-9650-26bb62263259
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e691301b-7484-40be-a3d4-c3bc590de959 # Content Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3039af57-d303-4062-bbf1-c1f2fdfff77c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 679fc2f5-3bb0-476e-b73d-2f005d78e991
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6a3feb81-50ce-467a-8aca-b5d4cc12aed0 # Description
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c1548cf1-2a39-4200-a4ad-9b863c8a5fa7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2bcee070-9832-4e9a-a3d1-51566028022e # OG Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5c9ea4f3-27b2-42df-af7f-30c8056c4bf9
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: f5c9fb9e-4023-4d68-b3da-091caf1070b8
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9ea88c8c-ff9b-40b0-94d4-e7eb1b8227a6 # Hero Optimisations
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 42ae0f9e-61fb-42b7-8cbd-df3a97817524
            userCondition: null
            warning: null
            width: 100
        name: 'Image Optimsation'
        uid: 3b47481d-f512-4b89-8a31-f5aa57f3769a
        userCondition: null
handle: contentPage
hasTitleField: true
name: 'Content Page'
section: ef841ba4-7bcd-4ef5-9c12-96377bf7fba2 # Pages
sortOrder: 3
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
