fieldLayouts:
  8615fe4d-ff3a-4082-9c81-417e96488ea9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: fbbfe0e2-7714-4fd6-8587-5719d19bcfd3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6652c1d5-4d7e-4102-b0d0-7c6133609c09 # Local Authority
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6623e4e1-b252-4ebd-b6f8-5987115db97d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 01d80304-2955-464a-afeb-6b88f964b51b # Local Authority (slug)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 15945f65-e05e-4509-a6c9-f6eb2f411a09
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 784bd961-34af-4cd9-95b0-388933b25647 # Locality
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5870ac2c-d69b-40c3-9900-3f07a0564692
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 55f66155-bf33-4ee8-a9fb-5dc0ad950b75 # Nomenclature of Territorial Units for Stastics Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 18a65406-8a52-40d2-8f1c-f2cc7e5d45d1
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e54a49c9-0078-484d-a129-f32bfc5e09c7 # Nomenclature of Territorial Units for Statistics
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6d7977c9-17ae-4dac-915a-85029f15222f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: f1400f56-551c-404d-a5fb-e73e3804942a # School Type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b75916ce-159b-43a1-b4c3-427c082b95f6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b1d331de-08d8-40d8-a186-8ccbb65e14ad # URN
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 27772404-b027-49a7-baa7-1da6b45ef5bb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 803a4c82-937b-4863-89b1-adc81cca7510
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 38e7414d-fa63-429c-bd9c-1cd523f702f2 # Street
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7d5403df-2b43-4c91-9c22-b4ffb1b4d926
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 10bd70ab-fb15-4522-a40e-e59b82bb493d # County
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 75c6344f-55de-4428-9c96-275a99501b31
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5926ab26-ed13-4347-80c3-1fbfcd1db6f4 # Town
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: abcedd4b-38d8-4f89-97ad-c1dfd0301c07
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 17a904c0-8155-41ee-bcd8-915ad0b0bc70 # Region
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 97470a3f-8dad-45fc-8691-d8df40542837
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 81626649-c471-4036-8abc-aa48cc1f1973 # Latitude
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e8a5d3fa-4352-4a99-9bf5-b7f11f2b3ca0
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 2f24b64b-245c-4788-9a05-af55af440b22 # Longitude
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 313104c6-14cd-47a6-b658-0a2286eaf3f0
            userCondition: null
            warning: null
            width: 50
        name: Address
        uid: 732d4738-6e7e-4f12-ba41-8c6dc8779ded
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 82486ff8-8d32-4b90-9828-8a12d879b242 # Schools
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
