fieldLayouts:
  1fb4cb30-83fc-4d00-ad05-16393ddb88fe:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 86811ed4-a4b6-412b-b327-41b8fab9ff3d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2527d118-70c9-4823-b988-4e155728eff8
        userCondition: null
handle: demoPage
hasTitleField: true
name: 'Demo Page'
section: ef841ba4-7bcd-4ef5-9c12-96377bf7fba2 # Pages
sortOrder: 10
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
