fieldLayouts:
  b0b01ba7-1bb0-44f5-961e-962a7ff6ca18:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f28dc24a-410d-4e97-a53e-025a81859ea8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cf635815-1a46-4527-9d6f-f0544d9019bf # Hero
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e612997-ae6e-4a0c-8638-99d2c3cb4d25
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 73929e5d-0eaa-424c-8cd1-ce83b47fd733 # Page Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e709c8a-f425-4269-9021-1350194f303c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 28cd8ba7-2c43-4bb7-bafe-6fb504d2ad90
        userCondition: null
handle: homepage
hasTitleField: false
name: Homepage
section: 54e60257-f31a-44aa-960e-bbd364197e28 # Homepage
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
