fieldLayouts:
  29456920-ac69-416e-9b72-d9e7baa46e32:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cd7b4619-0ed2-4071-83f6-ba8f9fe746e4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dbc7a062-ef19-48ca-bd6f-acda62a18b78 # Hero Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6c628c1e-8b5d-43c8-800b-198aa0424a9c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 73929e5d-0eaa-424c-8cd1-ce83b47fd733 # Page Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5d89735f-8968-4080-9c81-0de5dd6c6312
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8ef64660-77e7-479d-96ea-52bb8f4c8d23
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2bcee070-9832-4e9a-a3d1-51566028022e # OG Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4feb46a4-83d8-4a21-95bc-b658bb375b61
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6a3feb81-50ce-467a-8aca-b5d4cc12aed0 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eb316e63-5a8d-4904-8ecf-399d131e884a
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 6dc36b40-1cc5-4c1b-940d-5ee9c0ef84da
        userCondition: null
handle: landingPage
hasTitleField: true
name: 'Landing Page'
section: ef841ba4-7bcd-4ef5-9c12-96377bf7fba2 # Pages
sortOrder: 4
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
